name: oracle

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    environment:
      - ORACLE_PDB=mypdb
      - ORACLE_PWD=password
    ports:
      - 1521:1521
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
